### ISSUE TITLE
Bugged maps on the voting/rotation

### ISSUE THREAD

**Issue by kreator-eb** [kreator-eb/ebc-cj#2]
As Domi reported, the following maps are bugged, some are already known from before, a few of them have bad default map.gsc and need a fix, some are having mod compatibility issues and other problems.

```
mp_awe restarts to previous map (doesn't join it)
mp_insane restarts to previous map (doesn't join it)
mpvintage restarts to previous map (doesn't join it)
mp omnific (Server fatal crashed: script runtime error)
mp_bridge (Server fatal crashed: script runtime error)
mp_qube (Server fatal crashed: script compile error)
mp_mystic (Server Disconnected)
```

- [x]  Check the full list of available maps on the voting menu and server itself.

**Comment by kreator-eb** [comment]
Added new maps, will start checking old maps for compatibility issues.

**Comment by eBcLILOU** [comment]
Bug on maps rotation 

mp_mystic (Server crashed)
mp_planets (Server crashed)

**Comment by kreator-eb** [comment]
Mystic and Planets have been removed from the map pool. Will close the issue for now, all the other maps are working, might re add these two later down the road.

**Comment by eBcLILOU** [comment]
mp_to_the_moon (Fatal server crashed)

**Comment by kreator-eb** [comment]
Noted, if you find a working map from other servers please notify me.

**Comment by kreator-eb** [comment]
- Possible bugged map: mp_aether
- Bugged map: mp_to_the_moon

The rest of the maplist is checked and all maps are working as intended

**Comment by eBcLILOU** [comment]
- Bugged map : mp_bridge (server fatal crashed)
