### ISSUE TITLE
Spam Welcome Message

### ISSUE THREAD

**Issue by DominicanC** [kreator-eb/ebc-cj#8]
This spam Welcome message is due to when I joined, a Member was shooting me (spawn/spam kills) and the welcome messages as well as the Hold Save to Suicide was also spamming afterwards.

![spammsg](https://user-images.githubusercontent.com/48776113/55292265-7266be00-53b6-11e9-8eaf-6cf51af5e7c0.png)

**Comment by kreator-eb** [comment]
Issue has been resolved.
